import { v4 as uuidv4 } from "uuid";

export const illustrations = [
  {
    id: uuidv4(),
    path: "like-a-cannonball",
    type: "Cover Artwork",
    src: "/ALBIN/likeacannonball.png",
    wips: [
      "/ALBIN/LACB_WIP/1.png",
      "/ALBIN/LACB_WIP/2.png",
      "/ALBIN/LACB_WIP/3.png",
      "/ALBIN/LACB_WIP/4.png",
      "/ALBIN/LACB_WIP/5.png",
      "/ALBIN/LACB_WIP/6.png",
      "/ALBIN/LACB_WIP/7.png",
      "/ALBIN/LACB_WIP/8.png",
      "/ALBIN/LACB_WIP/9.png",
      "/ALBIN/LACB_WIP/10.png",
      "/ALBIN/LACB_WIP/11.png",
      "/ALBIN/LACB_WIP/12.png",
      "/ALBIN/LACB_WIP/13.png",
      "/ALBIN/LACB_WIP/14.png",
      "/ALBIN/LACB_WIP/15.png",
      "/ALBIN/LACB_WIP/16.png",
      "/ALBIN/LACB_WIP/17.png",
      "/ALBIN/LACB_WIP/18.png",
      "/ALBIN/LACB_WIP/19.png",
      "/ALBIN/LACB_WIP/20.png",
      "/ALBIN/LACB_WIP/21.png",
      "/ALBIN/LACB_WIP/22.png",
      "/ALBIN/LACB_WIP/23.png",
      "/ALBIN/LACB_WIP/24.png",
    ],
    alt: 'Cover artwork for Albin\'s "Like A Cannonball"',
    description: `Digital illustration for Albin's music single "Like A Cannonball".`,
    width: 1024,
    height: 1024,
    tools: [
      "Blender 3D",
      "Substance Designer",
      "Substance Painter",
      "Adobe Photoshop",
    ],
  },
  {
    id: uuidv4(),
    path: "love-in-slow-motion",
    type: "Cover Artwork",
    src: "/ALBIN/loveinslowmotion.png",
    wips: [
      "/ALBIN/LISM_WIP/1.png",
      "/ALBIN/LISM_WIP/2.png",
      "/ALBIN/LISM_WIP/3.png",
      "/ALBIN/LISM_WIP/4.png",
      "/ALBIN/LISM_WIP/5.png",
      "/ALBIN/LISM_WIP/6.png",
      "/ALBIN/LISM_WIP/7.png",
      "/ALBIN/LISM_WIP/8.png",
      "/ALBIN/LISM_WIP/9.png",
      "/ALBIN/LISM_WIP/10.png",
      "/ALBIN/LISM_WIP/11.png",
      "/ALBIN/LISM_WIP/12.png",
      "/ALBIN/LISM_WIP/13.png",
      "/ALBIN/LISM_WIP/14.png",
      "/ALBIN/LISM_WIP/15.png",
      "/ALBIN/LISM_WIP/16.png",
    ],
    alt: 'Cover artwork for Albin\'s "Love in Slow Motion"',
    description: `Digital illustration for Albin's music single "Love In Slow Motion".`,
    width: 1024,
    height: 1024,
    tools: ["Blender 3D", "Adobe Photoshop", "Adobe Illustrator"],
  },
  // {
  //   id: uuidv4(),
  //   path: "a-profound-waste-of-time",
  //   type: "Editorial Illustration",
  //   src: "/APWOT/apwot_0.png",
  //   alt: "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
  //   description: `Digital illustration for the second issue of A Profound Waste of Time magazine's second issue.`,
  //   width: 1820,
  //   height: 1024,
  //   tools: ["Blender 3D", "Adobe Photoshop", "Adobe Illustrator"],
  // },
  {
    id: uuidv4(),
    path: "a-profound-waste-of-time-pages-1-and-2",
    type: "Editorial Illustration",
    src: "/APWOT/apwot_1.png",
    alt: "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    description: `Pages 1-2 of an 8-pages spread illustration for A Profound Waste of Time magazine's second issue.`,
    width: 1581,
    height: 1024,
    tools: ["Blender 3D", "Adobe Photoshop", "Adobe Illustrator"],
  },
  {
    id: uuidv4(),
    path: "a-profound-waste-of-time-pages-3-and-4",
    type: "Editorial Illustration",
    src: "/APWOT/apwot_2.png",
    alt: "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    description: `Pages 3-4 of an 8-pages spread illustration for A Profound Waste of Time magazine's second issue.`,
    width: 1581,
    height: 1024,
    tools: ["Blender 3D", "Adobe Photoshop", "Adobe Illustrator"],
  },
  {
    id: uuidv4(),
    path: "a-profound-waste-of-time-pages-5-and-6",
    type: "Editorial Illustration",
    src: "/APWOT/apwot_3.png",
    alt: "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    description: `Pages 5-6 of an 8-pages spread illustration for A Profound Waste of Time magazine's second issue.`,
    width: 1581,
    height: 1024,
    tools: ["Blender 3D", "Adobe Photoshop", "Adobe Illustrator"],
  },
  {
    id: uuidv4(),
    path: "a-profound-waste-of-time-pages-7-and-8",
    type: "Editorial Illustration",
    src: "/APWOT/apwot_4.png",
    alt: "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    description: `Pages 7-8 of an 8-pages spread illustration for A Profound Waste of Time magazine's second issue.`,
    width: 1581,
    height: 1024,
    tools: ["Blender 3D", "Adobe Photoshop", "Adobe Illustrator"],
  },
  {
    id: uuidv4(),
    path: "gamesmaster-bookmark",
    type: "Bookmark Artwork",
    src: "/GAMESMASTER/bookmarks.png",
    alt: "Set of bookmark artwork for GamesMaster: A Oral History",
    description: `Set of bookmark artworks included in the GameMaster: A Oral History book.`,
    width: 1309,
    height: 1024,
    tools: ["Blender 3D", "Adobe Photoshop", "Adobe Illustrator"],
  },
  {
    id: uuidv4(),
    path: "breakfast-scene",
    type: "Personal Artwork",
    src: "/BREAKFAST/breakfast.png",
    alt: "Personal study for a breakfast scene",
    description: `Set of bookmark artworks included in the GameMaster: A Oral History book.`,
    width: 1448,
    height: 1024,
    tools: ["Blender 3D", "Adobe Photoshop"],
  },
  {
    id: uuidv4(),
    path: "commissioned-abstract-work-1",
    type: "Commissioned Artwork",
    src: "/CHASE/chase.png",
    alt: "Comissioned abstract artwork",
    width: 1024,
    height: 1024,
    tools: ["Blender 3D", "Adobe Photoshop"],
  },
  {
    id: uuidv4(),
    path: "tropical-scene",
    type: "Personal Artwork",
    src: "/TROPICALSCENE/tropicalscene.png",
    alt: "Personal study of a tropical scene",
    width: 1600,
    height: 800,
    tools: ["Blender 3D", "Adobe Photoshop", "Adobe Illustrator"],
  },
  {
    id: uuidv4(),
    path: "stella-comic-strip",
    type: "Digital Comic Strip",
    src: "/STELLA/stella.png",
    alt: "Digital comic strip for Stella",
    width: 1440,
    height: 900,
    tools: ["Blender 3D", "Adobe Photoshop"],
  },
  {
    id: uuidv4(),
    path: "helicopter",
    type: "Personal Artwork",
    src: "/HELICOPTER/helicopter.png",
    alt: "Personal study of a helicopter",
    width: 1820,
    height: 1024,
    tools: ["Blender 3D", "Adobe Photoshop"],
  },
];
