import { v4 as uuidv4 } from "uuid";

export const illustrations = [
  {
    id: uuidv4(),
    src: "/ALBIN/likeacannonball.png",
    alt: 'Cover artwork for Albin\'s "Like A Cannonball"',
    width: 1024,
    height: 1024,
  },
  {
    id: uuidv4(),
    src: "/ALBIN/loveinslowmotion.png",
    alt: 'Cover artwork for Albin\'s "Love in Slow Motion"',
    width: 1024,
    height: 1024,
  },
  {
    id: uuidv4(),
    src: "/APWOT/apwot_0.png",
    alt: "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    width: 1820,
    height: 1024,
  },
  {
    id: uuidv4(),
    src: "/APWOT/apwot_1.png",
    alt: "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    width: 1581,
    height: 1024,
  },
  {
    id: uuidv4(),
    src: "/APWOT/apwot_2.png",
    alt: "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    width: 1581,
    height: 1024,
  },
  {
    id: uuidv4(),
    src: "/APWOT/apwot_3.png",
    alt: "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    width: 1581,
    height: 1024,
  },
  {
    id: uuidv4(),
    src: "/APWOT/apwot_4.png",
    alt: "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    width: 1581,
    height: 1024,
  },
  {
    id: uuidv4(),
    src: "/GAMESMASTER/bookmarks.png",
    alt: "Set of bookmark artwork for GamesMaster: A Oral History",
    width: 1309,
    height: 1024,
  },
  {
    id: uuidv4(),
    src: "/BREAKFAST/breakfast.png",
    alt: "Personal study for a breakfast scene",
    width: 1448,
    height: 1024,
  },
  {
    id: uuidv4(),
    src: "/CHASE/chase.png",
    alt: "Comissioned abstract artwork",
    width: 1024,
    height: 1024,
  },
  {
    id: uuidv4(),
    src: "/TROPICALSCENE/tropicalscene.png",
    alt: "Personal study of a tropical scene",
    width: 1600,
    height: 800,
  },
  {
    id: uuidv4(),
    src: "/STELLA/stella.png",
    alt: "Digital comic strip for Stella",
    width: 1440,
    height: 900,
  },
  {
    id: uuidv4(),
    src: "/HELICOPTER/helicopter.png",
    alt: "Personal study of a helicopter",
    width: 1820,
    height: 1024,
  },
];
